version: "3"
services:
  node:
    container_name: node
    image: rchaser53/node-alpine
    tty: true
    working_dir: /home/app/workspace
    volumes:
      - ./workspace/:/home/app/workspace
    ports:
     - "3000:3000"