version: "3"
services:
  node:
    container_name: node
    image: rchaser53/node-alpine
    tty: true
    working_dir: /home/app/workspace
    volumes:
      - ./workspace/:/home/app/workspace
    ports:
     - "3000:3000"

  postgres:
    container_name: postgres
    image: postgres:9-alpine

  nginx:
    container_name: nginx
    image: nginx:alpine

  redis:
    container_name: redis
    image: redis:4.0.1-alpine
